### ISSUE TITLE
RuntimeError: normal expects all elements of std >= 0.0

### ISSUE THREAD

**Issue by prochalo** [ml-research/NeSyXIL#2]
When I ran train.py, I got the error below

**RuntimeError: normal expects all elements of std >= 0.0**

You can use the code below that confirms my issue (from the model.py)

```
b=32
n_s = 10
dim = 64
slots_mu = nn.Parameter(torch.randn(1, 1, dim))
slots_log_sigma = nn.Parameter(torch.randn(1, 1, dim))

mu = slots_mu.expand(b, n_s, -1)
sigma = slots_log_sigma.expand(b, n_s, -1)

slots = torch.normal(mu, sigma)
```

**Comment by wolfstam** [comment]
Hey thanks so much for interest in this repository and the issue message. This issue should be actually have been resolved with the last update to the NeSyConceptLearner repo (please see this closed issue for details: https://github.com/ml-research/NeSyXIL/issues/1).

If this for some reason does not suffice, please let me know.

**Comment by prochalo** [comment]
Thank you very much!
